# Generated by Django 2.2.19 on 2023-03-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
